## Handling a Imbalanced Dataset

In [ ]:
import numpy as np
import pandas as pd

# here we are createing a imbalaced dataset 
np.random.seed(123) #Fix random seed for reproduciblity
n_sample = 1000
class_0_ratio = 0.9
n_class_0 = int(n_sample * class_0_ratio)
n_class_1 = n_sample - n_class_0

In [3]:
n_class_0, n_class_1

(900, 100)

### Create Dataframe with imbalanced dataset

In [ ]:
class_0 = pd.DataFrame({
    'feature_1' : np.random.normal(loc=0,scale=1,size=n_class_0),
    'feature_2' : np.random.normal(loc=0,scale=1,size=n_class_0),
    'target':[0]*n_class_0
    }) # Majority class (Target = 0)


class_1 = pd.DataFrame({
    'feature_1' : np.random.normal(loc=2,scale=1,size=n_class_1),
    'feature_2' : np.random.normal(loc=2,scale=1,size=n_class_1),
    'target':[1]*n_class_1
    }) # Minority class (target = 1)

In [86]:
df=pd.concat([class_0,class_1]).reset_index(drop=True) #Combine both class

In [87]:
df.head()

   feature_1  feature_2  target
0  -1.085631   0.551302       0
1   0.997345   0.419589       0
2   0.282978   1.815652       0
3  -1.506295  -0.252750       0
4  -0.578600  -0.292004       0

In [88]:
df.tail()

     feature_1  feature_2  target
995   1.376371   2.845701       1
996   2.239810   0.880077       1
997   1.131760   1.640703       1
998   2.902006   0.390305       1
999   2.697490   2.013570       1

In [ ]:
df['target'].value_counts() # Verify

target
0    900
1    100
Name: count, dtype: int64

### (1) UP SAMPLING

In [ ]:
#Seprate majority and minority classes
df_minority=df[df['target']==1]
df_majority=df[df['target']==0]

In [ ]:

from sklearn.utils import resample
# Upsample minority class to match majority class
# replace=True allow repeatation sampling
df_minority_upsampled=resample(df_minority,replace=True, #Sample with replacement 
n_samples=len(df_majority),random_state=42)

In [ ]:
df_minority_upsampled.shape #new class cheak

(900, 3)

In [93]:
df_minority_upsampled.head()

     feature_1  feature_2  target
951   1.125854   1.843917       1
992   2.196570   1.397425       1
914   1.932170   2.998053       1
971   2.272825   3.034197       1
960   2.870056   1.550485       1

In [94]:
df_upsampled=pd.concat([df_majority,df_minority_upsampled])

In [95]:
df_upsampled['target'].value_counts()

target
0    900
1    900
Name: count, dtype: int64

### (2) Down Sampling

In [96]:
import numpy as np
import pandas as pd

np.random.seed(123)
n_sample = 1000
class_0_ratio = 0.9
n_class_0 = int(n_sample * class_0_ratio)
n_class_1 = n_sample - n_class_0


class_0 = pd.DataFrame({
    'feature_1' : np.random.normal(loc=0,scale=1,size=n_class_0),
    'feature_2' : np.random.normal(loc=0,scale=1,size=n_class_0),
    'target':[0]*n_class_0
    })


class_1 = pd.DataFrame({
    'feature_1' : np.random.normal(loc=2,scale=1,size=n_class_1),
    'feature_2' : np.random.normal(loc=2,scale=1,size=n_class_1),
    'target':[1]*n_class_1
    })


df=pd.concat([class_0,class_1]).reset_index(drop=True)

df['target'].value_counts() #Cheak the class distribution

target
0    900
1    100
Name: count, dtype: int64

In [ ]:
#downsampling
#Separate majority and minority classes 
df_minority=df[df['target']==1]
df_majority=df[df['target']==0]

In [ ]:

from sklearn.utils import resample
#downsample the majority class to match minor class size
#replace=false means no duplication sampling
df_majority_downsampled=resample(df_majority,replace=False, 
n_samples=len(df_minority),random_state=42)

In [99]:
df_majority_downsampled.shape # reduced to 100 from 900 to match df_minority

(100, 3)

In [ ]:
df_downsampled = pd.concat([df_majority_downsampled,df_minority]) #merge

In [101]:
df_downsampled['target'].value_counts() #Downsampling is bad because we are lossing datapoints

target
0    100
1    100
Name: count, dtype: int64

Revision:

Upsampling  = Increase minority class (duplicate samples).

Downsampling =  Reduce majority class (remove samples).

Upsampling risk = Overfitting.

Downsampling risk = Information loss.